name: quible-api
version: "3"
x-environment: &env
  ENV_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  ENV_EMAIL_ADDRESS: ${ENV_EMAIL_ADDRESS}
  ENV_EMAIL_PASSWORD: ${ENV_EMAIL_PASSWORD}
  ENV_JWT_SECRET: ${ENV_JWT_SECRET}
  ENV_URL_AUTH_SERVICE: "http://auth:${AUTH_PORT}"
  ENV_URL_APP_SERVICE: "http://app:${APP_PORT}"
  ENV_URL_DEMO_SERVICE: "http://demo:${DEMO_PORT}"
  IS_DOCKER: 1

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
      - ./dbInit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
  auth:
    build: 
      context: ./auth-service
      dockerfile: ../Dockerfile
      additional_contexts: 
        lib: ./lib
    restart: always
    environment:
      <<: *env
      PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"    
    depends_on:
      db:
        condition: service_healthy
  app:
    build: 
      context: ./app-service
      dockerfile: ../Dockerfile
      additional_contexts: 
        lib: ./lib
    restart: always
    environment:
      <<: *env
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    depends_on:
      db:
        condition: service_healthy
  demo:
    build: 
      context: ./demo-service
      dockerfile: ./Dockerfile
      # You can always switch back to the shared Dockerfile by replacing the above line with the one below
      # dockerfile: ../Dockerfile
      additional_contexts: 
        lib: ./lib
    restart: always
    environment:
      <<: *env
      PORT: ${DEMO_PORT}
    ports:
      - "${DEMO_PORT}:${DEMO_PORT}"
    depends_on:
      db:
        condition: service_healthy
  auth-old:
    build: ./auth-service-old
    restart: always
    profiles:
      - debug
    environment:
      <<: *env
      PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      db:
        condition: service_healthy