name: quible-api
version: "3"
x-environment: &env
  ENV_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  ENV_JWT_SECRET: ${ENV_JWT_SECRET}
  ENV_RSC_TOKEN: ${ENV_RSC_TOKEN}
  ENV_ABLY_KEY: ${ENV_ABLY_KEY}
  ENV_POSTMARK_API_KEY: ${ENV_POSTMARK_API_KEY}
  ENV_URL_AUTH_SERVICE: "http://auth:${AUTH_PORT}"
  ENV_URL_APP_SERVICE: "http://app:${APP_PORT}"
  IS_DOCKER: 1
x-context: &context
  lib: ./lib

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
  migrations:
    build: 
      context: ./cmd
      dockerfile: ./Dockerfile     
    environment:
      <<: *env 
    depends_on:
      db:
        condition: service_healthy
  auth:
    build: 
      context: ./auth-service
      dockerfile: ../Dockerfile
      additional_contexts: 
        <<: *context
    restart: always
    environment:
      <<: *env
      PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"    
    depends_on:
      migrations:
        condition: service_completed_successfully
  app:
    build: 
      context: ./app-service
      dockerfile: ../Dockerfile
      additional_contexts: 
        <<: *context            
    restart: always
    environment:
      <<: *env
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    depends_on:
      - auth