basePath: /api/v1
definitions:
  RSC.InjuryItem:
    properties:
      injuries:
        items:
          $ref: '#/definitions/RSC.PlayerInjuryItem'
        type: array
      team:
        type: string
      team_id:
        type: integer
    type: object
  RSC.PlayerInfoItem:
    properties:
      age:
        type: string
      college:
        type: string
      height:
        type: string
      number:
        type: integer
      player:
        type: string
      player_id:
        type: integer
      position:
        $ref: '#/definitions/RSC.PlayerPosition'
      position_category:
        $ref: '#/definitions/RSC.PlayerPosition'
      status:
        $ref: '#/definitions/RSC.PlayerStatus'
      team:
        type: string
      team_id:
        type: integer
      weight:
        type: integer
    type: object
  RSC.PlayerInjuryItem:
    properties:
      date_injured:
        type: string
      injury:
        type: string
      player:
        type: string
      player_id:
        type: string
      returns:
        type: string
    type: object
  RSC.PlayerPosition:
    enum:
    - C
    - F
    - G
    - FC
    - GF
    - SF
    - SG
    - PF
    - PG
    type: string
    x-enum-varnames:
    - C
    - F
    - G
    - FC
    - GF
    - SF
    - SG
    - PF
    - PG
  RSC.PlayerSeasonStatItem:
    properties:
      player:
        type: string
      player_id:
        type: integer
      postseason:
        $ref: '#/definitions/RSC.PlayerStatItem'
      regular_season:
        $ref: '#/definitions/RSC.PlayerStatItem'
      team:
        type: string
      team_id:
        type: integer
    type: object
  RSC.PlayerStatItem:
    properties:
      assists:
        type: integer
      blocks:
        type: integer
      defensive_rebounds:
        type: integer
      field_goals_attempted:
        type: integer
      field_goals_made:
        type: integer
      fouls:
        type: integer
      free_throws_attempted:
        type: integer
      free_throws_made:
        type: integer
      games_played:
        type: integer
      minutes:
        type: integer
      offensive_rebounds:
        type: integer
      points:
        type: integer
      steals:
        type: integer
      three_points_attempted:
        type: integer
      three_points_made:
        type: integer
      total_rebounds:
        type: integer
      turnovers:
        type: integer
      two_points_attempted:
        type: integer
      two_points_made:
        type: integer
    type: object
  RSC.PlayerStatus:
    enum:
    - ACT
    - INACT
    - QUES
    type: string
    x-enum-varnames:
    - Act
    - Inact
    - Ques
  RSC.ScheduleEventName:
    enum:
    - First Round
    - Semifinals
    - Conference Finals
    - NBA Finals
    type: string
    x-enum-varnames:
    - FirstRound
    - Semifinals
    - ConferenceFinals
    - NBAFinals
  RSC.ScheduleItem:
    properties:
      away_team:
        type: string
      away_team_ID:
        type: integer
      broadcast:
        type: string
      event_name:
        $ref: '#/definitions/RSC.ScheduleEventName'
      game_ID:
        type: string
      game_time:
        type: string
      home_team:
        type: string
      home_team_ID:
        type: integer
      round:
        $ref: '#/definitions/RSC.ScheduleRound'
      season:
        type: string
      season_type:
        $ref: '#/definitions/RSC.ScheduleType'
      status:
        $ref: '#/definitions/RSC.ScheduleStatus'
    type: object
  RSC.ScheduleRound:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - One
    - Two
    - Three
    - Four
  RSC.ScheduleStatus:
    enum:
    - scheduled
    - delayed
    - postponed
    - suspended
    - canceled
    - inprogress
    - final
    - completed
    type: string
    x-enum-varnames:
    - Scheduled
    - Delayed
    - Postponed
    - Suspended
    - Canceled
    - Inprogress
    - Final
    - Completed
  RSC.ScheduleType:
    enum:
    - Preseason
    - Regular Season
    - Postseason
    type: string
    x-enum-varnames:
    - Preseason
    - RegularSeason
    - Postseason
  RSC.TeamInfoItem:
    properties:
      abbrv:
        type: string
      arena:
        type: string
      conf:
        type: string
      location:
        type: string
      mascot:
        type: string
      team:
        type: string
      team_id:
        type: integer
    type: object
  RSC.TeamSeasonStatItem:
    properties:
      postseason:
        $ref: '#/definitions/RSC.TeamStatItem'
      regular_season:
        $ref: '#/definitions/RSC.TeamStatItem'
      team:
        type: string
      team_id:
        type: integer
    type: object
  RSC.TeamStatItem:
    properties:
      assists:
        type: integer
      blocks:
        type: integer
      defensive_rebounds:
        type: integer
      field_goals_attempted:
        type: integer
      field_goals_made:
        type: integer
      fouls:
        type: integer
      free_throws_attempted:
        type: integer
      free_throws_made:
        type: integer
      games_played:
        type: integer
      losses:
        type: integer
      offensive_rebounds:
        type: integer
      points:
        type: integer
      steals:
        type: integer
      three_points_attempted:
        type: integer
      three_points_made:
        type: integer
      total_rebounds:
        type: integer
      turnovers:
        type: integer
      two_points_attempted:
        type: integer
      two_points_made:
        type: integer
      wins:
        type: integer
    type: object
  controller.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: www.quible.io
info:
  contact: {}
  description: Wrapper to RSC API
  title: Quible app-service
  version: "0.1"
paths:
  /daily-schedule:
    get:
      description: Returns list of games for the next 7 days
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      - description: Game ID
        in: query
        name: game_id
        type: string
      - default: now
        description: Report for date and 7 days in advance
        example: "2023-11-23"
        format: date
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.ScheduleItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get Daily Schedule
      tags:
      - RSC
      - private
  /docs:
    get:
      description: Render Swagger UI page
      parameters:
      - default: swagger
        description: UI template
        enum:
        - swagger
        - rapidoc
        - redoc
        in: query
        name: ui
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Swagger UI
      tags:
      - docs
  /docs/errors:
    get:
      description: Renders list of erros reported by microservice
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Error Codes UI
      tags:
      - docs
  /docs/spec:
    get:
      description: Swagger spec in YAML format
      produces:
      - application/yaml
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Swagger spec
      tags:
      - docs
  /injuries:
    get:
      description: Returns list of recorded players injuries
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.InjuryItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get players injuries
      tags:
      - RSC
      - private
  /player-info:
    get:
      description: Returns list of players of all or selected team
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.PlayerInfoItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get list of players
      tags:
      - RSC
      - private
  /player-stats:
    get:
      description: Returns players stats for the selected season
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      - description: Player ID
        in: query
        name: player_id
        type: integer
      - default: <current season>
        description: Beginning of sport season
        example: "2023"
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.PlayerSeasonStatItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get player(s) stats
      tags:
      - RSC
      - private
  /schedule-season:
    get:
      description: Returns list of games for the selected season
      parameters:
      - default: <current season>
        description: Sport season
        example: "2023"
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.ScheduleItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get Schedule for Season
      tags:
      - RSC
      - private
  /team-info:
    get:
      description: Returns list of teams or a single team info
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.TeamInfoItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get list of teams
      tags:
      - RSC
      - private
  /team-stats:
    get:
      description: Returns teams stats for the selected season
      parameters:
      - description: Team ID
        in: query
        name: team_id
        type: integer
      - default: <current season>
        description: Beginning of sport season
        example: "2023"
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/RSC.TeamSeasonStatItem'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get team(s) stats
      tags:
      - RSC
      - private
swagger: "2.0"
