// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Err207_SomeDataUndeleted-2071001]
	_ = x[Err400_EmailNotRegistered-4001001]
	_ = x[Err400_InvalidEmailFormat-4001002]
	_ = x[Err400_InvalidUsernameFormat-4001003]
	_ = x[Err400_InvalidPhoneFormat-4001004]
	_ = x[Err400_UserWithUsernameExists-4001005]
	_ = x[Err400_UserWithEmailExists-4001006]
	_ = x[Err400_IsufficientPasswordComplexity-4001007]
	_ = x[Err400_MalformedJSON-4001008]
	_ = x[Err400_InvalidRequestBody-4001009]
	_ = x[Err400_FileTooLarge-4001010]
	_ = x[Err400_InvalidClientId-4001011]
	_ = x[Err401_InvalidCredentials-4011001]
	_ = x[Err401_AuthorizationHeaderMissing-4011002]
	_ = x[Err401_AuthorizationHeaderInvalid-4011003]
	_ = x[Err401_AuthorizationExpired-4011004]
	_ = x[Err401_InvalidRefreshToken-4011005]
	_ = x[Err401_UserNotFound-4011006]
	_ = x[Err403_CannotToDelete-4031001]
	_ = x[Err403_CannotEditPhone-4031002]
	_ = x[Err404_PlayerStatsNotFound-4041001]
	_ = x[Err404_UserOrPhoneNotFound-4041002]
	_ = x[Err404_AccountNotFound-4041003]
	_ = x[Err404_UserNotFound-4041004]
	_ = x[Err404_UserHasNoImage-4041005]
	_ = x[Err424_UnknownError-4241001]
	_ = x[Err429_EditRequestTimedOut-4291001]
	_ = x[Err500_UnknownError-5001001]
	_ = x[Err500_UnableToDelete-5001002]
	_ = x[Err500_UnableToEditPhone-5001003]
	_ = x[Err500_UnableToRegister-5001004]
	_ = x[Err500_UnableToGenerateToken-5001005]
	_ = x[Err503_DataBaseOnDelete-5031001]
	_ = x[Err503_DataBaseOnPhoneEdit-5031002]
}

const (
	_ErrorCode_name_0 = "Err207_SomeDataUndeleted"
	_ErrorCode_name_1 = "Err400_EmailNotRegisteredErr400_InvalidEmailFormatErr400_InvalidUsernameFormatErr400_InvalidPhoneFormatErr400_UserWithUsernameExistsErr400_UserWithEmailExistsErr400_IsufficientPasswordComplexityErr400_MalformedJSONErr400_InvalidRequestBodyErr400_FileTooLargeErr400_InvalidClientId"
	_ErrorCode_name_2 = "Err401_InvalidCredentialsErr401_AuthorizationHeaderMissingErr401_AuthorizationHeaderInvalidErr401_AuthorizationExpiredErr401_InvalidRefreshTokenErr401_UserNotFound"
	_ErrorCode_name_3 = "Err403_CannotToDeleteErr403_CannotEditPhone"
	_ErrorCode_name_4 = "Err404_PlayerStatsNotFoundErr404_UserOrPhoneNotFoundErr404_AccountNotFoundErr404_UserNotFoundErr404_UserHasNoImage"
	_ErrorCode_name_5 = "Err424_UnknownError"
	_ErrorCode_name_6 = "Err429_EditRequestTimedOut"
	_ErrorCode_name_7 = "Err500_UnknownErrorErr500_UnableToDeleteErr500_UnableToEditPhoneErr500_UnableToRegisterErr500_UnableToGenerateToken"
	_ErrorCode_name_8 = "Err503_DataBaseOnDeleteErr503_DataBaseOnPhoneEdit"
)

var (
	_ErrorCode_index_1 = [...]uint16{0, 25, 50, 78, 103, 132, 158, 194, 214, 239, 258, 280}
	_ErrorCode_index_2 = [...]uint8{0, 25, 58, 91, 118, 144, 163}
	_ErrorCode_index_3 = [...]uint8{0, 21, 43}
	_ErrorCode_index_4 = [...]uint8{0, 26, 52, 74, 93, 114}
	_ErrorCode_index_7 = [...]uint8{0, 19, 40, 64, 87, 115}
	_ErrorCode_index_8 = [...]uint8{0, 23, 49}
)

func (i ErrorCode) String() string {
	switch {
	case i == 2071001:
		return _ErrorCode_name_0
	case 4001001 <= i && i <= 4001011:
		i -= 4001001
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 4011001 <= i && i <= 4011006:
		i -= 4011001
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 4031001 <= i && i <= 4031002:
		i -= 4031001
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	case 4041001 <= i && i <= 4041005:
		i -= 4041001
		return _ErrorCode_name_4[_ErrorCode_index_4[i]:_ErrorCode_index_4[i+1]]
	case i == 4241001:
		return _ErrorCode_name_5
	case i == 4291001:
		return _ErrorCode_name_6
	case 5001001 <= i && i <= 5001005:
		i -= 5001001
		return _ErrorCode_name_7[_ErrorCode_index_7[i]:_ErrorCode_index_7[i+1]]
	case 5031001 <= i && i <= 5031002:
		i -= 5031001
		return _ErrorCode_name_8[_ErrorCode_index_8[i]:_ErrorCode_index_8[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
