// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChatUser       string
	Chats          string
	GooseDBVersion string
	Images         string
	TeamInfo       string
	Users          string
}{
	ChatUser:       "chat_user",
	Chats:          "chats",
	GooseDBVersion: "goose_db_version",
	Images:         "images",
	TeamInfo:       "team_info",
	Users:          "users",
}
