// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion string
	Images         string
	TeamInfo       string
	Teams          string
	Users          string
}{
	GooseDBVersion: "goose_db_version",
	Images:         "images",
	TeamInfo:       "team_info",
	Teams:          "teams",
	Users:          "users",
}
