name: CI Lint and Test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    # container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./auth-service
  test_auth_service:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test auth-service
        run: |
          cd auth-service
          go test ./...
  test_demo_service:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test demo-service
        run: |
          cd demo-service
          go test ./...
  test_lib:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test lib
        run: |
          cd lib
          go test ./...