name: CI Lint and Test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint_all:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint auth-service
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./auth-service
      - name: golangci-lint app-service
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./app-service
      - name: golangci-lint lib
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ./lib

  test_all:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test auth-service
        run: |
          cd auth-service
          go test ./...
      - name: Test demo-service
        run: |
          cd demo-service
          go test ./...
      - name: Test lib
        run: |
          cd lib
          go test ./...