name: CI Lint and Test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    # container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          # git config --global --add safe.directory /__w/quible-api/quible-api
          git status
      - name: Install golangci-lint
        # run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        run: sudo apt-get install golangci-lint
      - name: Lint auth-service
        run: golangci-lint run ./auth-service/...
      - name: Lint demo-service
        run: golangci-lint run ./demo-service/...
      - name: Lint lib
        run: golangci-lint run ./lib/...
  test_auth_service:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test auth-service
        run: |
          cd auth-service
          go test ./...
  test_demo_service:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test demo-service
        run: |
          cd demo-service
          go test ./...
  test_lib:
    runs-on: ubuntu-latest
    container: golang:latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test lib
        run: |
          cd lib
          go test ./...